# Generated by Django 4.0.6 on 2023-05-05 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=230)),
                ('email', models.EmailField(max_length=254)),
                ('time', models.CharField(default='', max_length=12)),
                ('phone', models.CharField(default='', max_length=30)),
                ('people', models.IntegerField(default='')),
                ('message', models.TextField(blank=True, max_length=300, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewapp.restaurant')),
            ],
        ),
    ]
