# Generated by Django 4.0.6 on 2023-05-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0002_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table',
        ),
    ]
